version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hexcore
    restart: on-failure
    ports:
      - 3327:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hexcore_db
      MYSQL_USER: hexcore_user
      MYSQL_PASSWORD: hexcore_password
    volumes:
      - mysql-data:/var/lib/mysql # Persistent volume for MySQL data
  
  redis:
    image: redis:7.0
    container_name: redis-hexcore
    restart: on-failure
    ports:
      - 6327:6379
    environment:
      REDIS_PASSWORD: redispassword

volumes:
  mysql-data:
